Repository nextcloud/external, pull requests merged in 2019-10, with the labels that each got.

#54 Allow fullscreen within iframe
  templates/frame.php
Labels: 3. to review, enhancement

#149 resize iframe immediately after load, fixes #148
  js/external.js
Labels: 3. to review, bug

#150 Set CSP for icons
  lib/Controller/IconController.php
Labels: 3. to review, backport-request, bug

#158 Make sure the white image also has 32px width
  css/style.css
Labels: 3. to review, backport-request, bug
