Repository nextcloud/external, pull requests merged in 2022-10, with the labels that each got.

#317 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#316 [master] Update nextcloud/ocp dependency
  composer.lock
  lib/Controller/SiteController.php
Labels: 3. to review, dependencies

#310 Implement JWT tokens for external site links
  .github/dependabot.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .gitignore
  Makefile
  composer.json
  composer.lock
  docs/jwt-sample.php
  lib/BeforeTemplateRenderedListener.php
  lib/Capabilities.php
  lib/JWTManager.php
  lib/Settings/Admin.php
  lib/Settings/Personal.php
  lib/SitesManager.php
  psalm.xml
  templates/settings.php
  tests/psalm-baseline.xml
  vendor-bin/csfixer/composer.json
  vendor-bin/csfixer/composer.lock
  vendor-bin/mozart/composer.json
  vendor-bin/mozart/composer.lock
  vendor-bin/phpunit/composer.json
  vendor-bin/phpunit/composer.lock
  vendor-bin/psalm/composer.json
  vendor-bin/psalm/composer.lock
Labels: 3. to review, enhancement

#340 Updating psalm.yml workflow from template
  .github/workflows/psalm.yml
Labels: dependencies

#336 Updating lint-php-cs.yml workflow from template
  .github/workflows/lint-php-cs.yml
Labels: dependencies

#338 Updating phpunit-pgsql.yml workflow from template
  .github/workflows/phpunit-pgsql.yml
Labels: dependencies

#339 Updating phpunit-sqlite.yml workflow from template
  .github/workflows/phpunit-sqlite.yml
Labels: dependencies

#337 Updating phpunit-mysql.yml workflow from template
  .github/workflows/phpunit-mysql.yml
Labels: dependencies

#341 [master] Update nextcloud/ocp dependency
  composer.lock
  vendor-bin/csfixer/composer.lock
  vendor-bin/mozart/composer.lock
  vendor-bin/psalm/composer.lock
Labels: 3. to review, dependencies

#344 Bump version
  CHANGELOG.md
  appinfo/info.xml
Labels: backport-request

#349 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#348 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#355 [stable25] Update nextcloud/ocp dependency
  composer.lock
  vendor-bin/csfixer/composer.lock
  vendor-bin/mozart/composer.lock
  vendor-bin/phpunit/composer.lock
  vendor-bin/psalm/composer.lock
Labels: 3. to review, dependencies

#354 [master] Update nextcloud/ocp dependency
  composer.lock
  vendor-bin/csfixer/composer.lock
  vendor-bin/mozart/composer.lock
  vendor-bin/psalm/composer.lock
Labels: 3. to review, dependencies
