Repository nextcloud/external, pull requests merged in 2023-08, with the labels that each got.

#524 [stable26] Update nextcloud/ocp dependency
  .github/workflows/lint-info-xml.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/phpunit-summary-when-unrelated.yml
  composer.lock
Labels: 3. to review, dependencies, feedback-requested

#533 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#504 chore: update node engines to next LTS
  package-lock.json
  package.json
Labels: 3. to review, dependencies, automated, feedback-requested

#534 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies, feedback-requested

#541 Fix quota links in files
  js/quota-files-sidebar.js
  lib/BeforeTemplateRenderedListener.php
  package-lock.json
  package.json
  src/quota-files-sidebar.js
  webpack.config.js
Labels: backport-request
