Repository nextcloud/external, pull requests merged in 2023-07, with the labels that each got.

#485 chore(CI): Adjust testing matrix for Nextcloud 27 on stable27
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  composer.json
  composer.lock
Labels: feedback-requested

#460 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#529 [stable25] Fix the phpunit CI
  .github/workflows/phpunit-mysql.yml
Labels: 3. to review, backport-request

#525 [stable25] Update nextcloud/ocp dependency
  .github/workflows/lint-info-xml.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  composer.json
  composer.lock
Labels: 3. to review, dependencies, feedback-requested
