Repository nextcloud/external, pull requests merged in 2024-06, with the labels that each got.

#713 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#714 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#710 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#694 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#715 chore(CI): Updating pr-feedback.yml workflow from template
  .github/workflows/pr-feedback.yml
Labels: dependencies

#718 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#719 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#720 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#721 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#724 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#725 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#726 refactor: Use PHP types for all Controller methods
  composer.json
  lib/Controller/APIController.php
  lib/Controller/IconController.php
  lib/Controller/SiteController.php
  lib/SitesManager.php
Labels: 3. to review, technical debt

#690 Updating appstore-build-publish.yml workflow from template
  .github/workflows/appstore-build-publish.yml
Labels: dependencies

#731 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#733 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#732 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
