Repository nextcloud/external, pull requests merged in 2024-04, with the labels that each got.

#662 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#680 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#664 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#687 Add reuse compliance badge
  README.md
Labels: 4. to release

#688 Updating reuse.yml workflow from template
  .github/workflows/reuse.yml
Labels: dependencies

#689 Updating pr-feedback.yml workflow from template
  .github/workflows/pr-feedback.yml
Labels: dependencies

#686 Updating node.yml workflow from template
  .github/workflows/node.yml
  LICENSES/MIT.txt
Labels: dependencies
