Repository nextcloud/external, pull requests merged in 2024-07, with the labels that each got.

#734 chore(CI): Updating reuse.yml workflow from template
  .github/workflows/reuse.yml
Labels: dependencies

#735 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#739 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/node.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review, dependencies, automated

#742 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#740 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#741 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#744 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#745 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#750 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#752 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#753 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
